---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiyakun?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  profiles: dev1
mybatis: 
  mapper-locations: classpath:mapper/*.xml
server:
  port: 20000

---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiyakun?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  profiles: dev2
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.shi.quartzdemo.entity
server:
  port: 20001
    